export const roleOptions = [
  { title: "admin", value: "admin" },
  { title: "account admin", value: "account_admin" },
  { title: "store incharge", value: "store_incharge" },
  { title: "general user", value: "general_user" },
  { title: "salesman", value: "salesman" },
];

export const productUnitOptions = [
  { label: "piece", value: "piece" },
  { label: "box", value: "box" },
  { label: "bottle", value: "bottle" },
  { label: "unit", value: "unit" },
  { label: "ml", value: "ml" },
  { label: "liter", value: "liter" },
  { label: "mg", value: "mg" },
  { label: "gram", value: "gram" },
  { label: "kg", value: "kg" },
  { label: "tablet", value: "tablet" },
  { label: "capsule", value: "capsule" },
  { label: "pack", value: "pack" },
  { label: "strip", value: "strip" },
  { label: "sachet", value: "sachet" },
  { label: "vial", value: "vial" },
  { label: "ampoule", value: "ampoule" },
  { label: "drop", value: "drop" },
  { label: "patch", value: "patch" },
  { label: "tube", value: "tube" },
  { label: "jar", value: "jar" },
  { label: "can", value: "can" },
  { label: "roll", value: "roll" },
  { label: "carton", value: "carton" },
  { label: "pouch", value: "pouch" },
  { label: "dozen", value: "dozen" },
  { label: "tray", value: "tray" },
  { label: "bag", value: "bag" },
  { label: "sack", value: "sack" },
  { label: "bundle", value: "bundle" },
  { label: "set", value: "set" },
  { label: "pack", value: "pack" },
  { label: "slice", value: "slice" },
  { label: "loaf", value: "loaf" },
  { label: "head", value: "head" },
  { label: "bunch", value: "bunch" },
  { label: "bar", value: "bar" },
  { label: "gallon", value: "gallon" },
  { label: "quart", value: "quart" },
  { label: "pint", value: "pint" },
  { label: "cup", value: "cup" },
  { label: "ounce", value: "ounce" },
  { label: "pinch", value: "pinch" },
];

export const statusOptions = [
  { title: "active", value: "active" },
  { title: "deactive", value: "deactive" },
];

export const genderOptions = [
  { title: "Male", value: "male" },
  { title: "Female", value: "female" },
  { title: "Other", value: "other" },
];

export const paymentMethodOptions = [
  { title: "cash", value: "cash" },
  { title: "card", value: "card" },
  { title: "bank", value: "bank" },
  { title: "bkash", value: "bkash" },
  { title: "rocket", value: "rocket" },
  { title: "mobile-banking", value: "mobile-banking" },
];

export const refundMethodOptions = [
  { title: "cash", value: "cash" },
  { title: "card", value: "card" },
  { title: "bank", value: "bank" },
  { title: "bkash", value: "bkash" },
  { title: "rocket", value: "rocket" },
  { title: "mobile-banking", value: "mobile-banking" },
];

export const taxOptions = [
  { title: "Value-Added-Tax (VAT)", value: "vat" },
  { title: "Income tax", value: "income-tax" },
  { title: "Corporation tax", value: "corporate-tax" },
  { title: "Supplementary duty", value: "supplementary-duty" },
  { title: "Customs duties", value: "customs-duties" },
];

export const medicineFormulationOptions = [
  { label: "Tablets", value: "Tablets" },
  { label: "Compressed Tablets", value: "Compressed Tablets" },
  { label: "Coated Tablets", value: "Coated Tablets" },
  { label: "Effervescent Tablets", value: "Effervescent Tablets" },
  {
    label: "Orally Disintegrating Tablets (ODTs)",
    value: "Orally Disintegrating Tablets (ODTs)",
  },
  { label: "Sustained-Release Tablets", value: "Sustained-Release Tablets" },
  { label: "Capsules", value: "Capsules" },
  { label: "Hard Gelatin Capsules", value: "Hard Gelatin Capsules" },
  { label: "Soft Gelatin Capsules", value: "Soft Gelatin Capsules" },
  { label: "Powders", value: "Powders" },
  { label: "Oral Powders", value: "Oral Powders" },
  { label: "Effervescent Powders", value: "Effervescent Powders" },
  { label: "Granules", value: "Granules" },
  { label: "Effervescent Granules", value: "Effervescent Granules" },
  { label: "Sustained-Release Granules", value: "Sustained-Release Granules" },
  { label: "Solutions", value: "Solutions" },
  { label: "Oral Solutions", value: "Oral Solutions" },
  { label: "Injectable Solutions", value: "Injectable Solutions" },
  { label: "Eye/Ear Drops", value: "Eye/Ear Drops" },
  { label: "Suspensions", value: "Suspensions" },
  { label: "Oral Suspensions", value: "Oral Suspensions" },
  { label: "Injectable Suspensions", value: "Injectable Suspensions" },
  { label: "Topical Suspensions", value: "Topical Suspensions" },
  { label: "Emulsions", value: "Emulsions" },
  { label: "Oral Emulsions", value: "Oral Emulsions" },
  { label: "Injectable Emulsions", value: "Injectable Emulsions" },
  { label: "Topical Emulsions", value: "Topical Emulsions" },
  { label: "Syrups", value: "Syrups" },
  { label: "Flavored Syrups", value: "Flavored Syrups" },
  { label: "Medicinal Syrups", value: "Medicinal Syrups" },
  { label: "Elixirs", value: "Elixirs" },
  { label: "Hydroalcoholic Solutions", value: "Hydroalcoholic Solutions" },
  { label: "Tinctures", value: "Tinctures" },
  { label: "Alcoholic Extracts", value: "Alcoholic Extracts" },
  { label: "Creams", value: "Creams" },
  { label: "Aqueous Creams", value: "Aqueous Creams" },
  { label: "Oily Creams", value: "Oily Creams" },
  { label: "Ointments", value: "Ointments" },
  { label: "Hydrophobic Ointments", value: "Hydrophobic Ointments" },
  { label: "Hydrophilic Ointments", value: "Hydrophilic Ointments" },
  { label: "Gels", value: "Gels" },
  { label: "Aqueous Gels", value: "Aqueous Gels" },
  { label: "Non-Aqueous Gels", value: "Non-Aqueous Gels" },
  { label: "Pastes", value: "Pastes" },
  { label: "Suppositories", value: "Suppositories" },
  { label: "Rectal Suppositories", value: "Rectal Suppositories" },
  { label: "Vaginal Suppositories", value: "Vaginal Suppositories" },
  { label: "Inhalers", value: "Inhalers" },
  {
    label: "Metered Dose Inhalers (MDIs)",
    value: "Metered Dose Inhalers (MDIs)",
  },
  { label: "Dry Powder Inhalers (DPIs)", value: "Dry Powder Inhalers (DPIs)" },
  { label: "Nebulizers", value: "Nebulizers" },
  { label: "Aerosols", value: "Aerosols" },
  { label: "Topical Aerosols", value: "Topical Aerosols" },
  { label: "Nasal Aerosols", value: "Nasal Aerosols" },
  { label: "Patches", value: "Patches" },
  { label: "Transdermal Patches", value: "Transdermal Patches" },
  { label: "Gels and Ointments", value: "Gels and Ointments" },
  { label: "Lozenges", value: "Lozenges" },
  { label: "Lollipops", value: "Lollipops" },
  { label: "Chewable Tablets", value: "Chewable Tablets" },
  { label: "Buccal Tablets", value: "Buccal Tablets" },
  { label: "Sublingual Tablets", value: "Sublingual Tablets" },
];
